### ISSUE TITLE
1.x LTS 版本路线图 | 1.x LTS Version Roadmap 

### ISSUE THREAD

**Issue by getneko** [getneko/getneko-desktop#2]
- [ ] 发布测试bata版本 | Release test beta version  
- [ ] 发布第一个稳定版 | Release the first stable version 
- [ ] 完成对docker的支持 | Complete support for Docker 
- [ ] 完成对1.22编译器的支持 | Complete support for the 1.22 compiler
- [ ] 完成对多种数据库的支持 | Complete support for multiple databases
- [ ] 完成桌面端对linux的支持 | Complete desktop support for Linux 
- [ ] 发布flatpak发行版 | Release Flatpak package
- [ ] 完成对 swagger 2.0 的支持  | Complete support for Swagger 2.0
